# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_auto_20170116_2047"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Tagged",
        ),
    ]
