# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_auto_20170209_1506"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.AddField(
            model_name="tagged",
            name="tag",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="tags.Tag"
            ),
        ),
    ]
