# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0005_auto_20170209_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
