# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0008_auto_20170209_1549"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagged",
            options={"ordering": ("tag__name",)},
        ),
        migrations.AlterField(
            model_name="tagged",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged",
                to="tags.Tag",
            ),
        ),
    ]
