# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0009_auto_20170210_1006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagged',
            unique_together=set([('tag', 'tagged_id', 'tagged_type')]),
        ),
    ]
