# Generated by Django 2.1.9 on 2019-06-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0010_auto_20170622_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagged',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tagged',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagged',
            name='tagged_type',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tagged',
        ),
    ]
