# Generated by Django 2.2 on 2022-05-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestalten', '0016_auto_20210421_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltinNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gestalten.Gestalt')),
            ],
        ),
    ]
