image: git-registry.hack-hro.de:443/stadtgestalten/stadtgestalten/build:buster
variables:
    # Do not use the 'build/' subdirectory, since this would get cleanup up during 'dist-deb'.
    # This directory needs to be listed in debian/source/options in 'extend-diff-ignore'.
    virtualenv_directory: "$CI_PROJECT_DIR/gitlab-ci-build-venv"

before_script:
    - virtualenv -p python3 --system-site-packages "$virtualenv_directory"
    - source "$virtualenv_directory/bin/activate"
    - pip install --upgrade pip
    - pip install -r requirements.txt

make_test:
    stage: test
    script:
        # stadt.settings is required for the tests
        - make app_local_settings
        - make lint
        - make test

# The latest built deb package is available under the following URL:
#   https://git.hack-hro.de/stadtgestalten/stadtgestalten/builds/artifacts/master/raw/build/debian/export/stadtgestalten.deb?job=deb-package
make_deb_package:
    stage: build
    except:
        - tags
    script:
        - make dist-deb DEBIAN_BUILDPACKAGE_COMMAND="dpkg-buildpackage --no-sign"
        # turn the symlink of the orig tarball into a real file
        - a=$(ls build/debian/grouprise_*.orig.tar.gz) && cp -L "$a" "$a.tmp" && mv "$a.tmp" "$a"
    artifacts:
        name: grouprise-deb
        paths:
            - build/debian
        exclude:
            # omit the full build directory (including the huge "node_modules" directory)
            - build/debian/grouprise-*/**
        expire_in: 1w

make_deb_package_release:
    stage: deploy
    only:
        - tags
        - web
    script:
        - make dist-deb DEBIAN_BUILDPACKAGE_COMMAND="dpkg-buildpackage --no-sign"
    artifacts:
        paths:
            - build/debian
        expire_in: 1000 yrs

deb_package_test:
    stage: test
    dependencies:
      - make_deb_package
    script:
      # we are running autopkgtest manually, thus we need to ensure manually, that all dependencies are fulfilled
      - "apt-get install -y $(grep '^Depends: ' debian/tests/control | cut -f 2- -d ' ' | tr -d ',' | tr ' ' '\n' | sort | uniq | grep -v grouprise)"
      # the package "moreutils" is only a grouprise dependency (not a build dependency), thus it is missing from the docker image
      - apt-get install moreutils
      - dpkg -i build/debian/grouprise_*.deb build/debian/grouprise-dependencies_*.deb
      - apt-get install -y autopkgtest
      - autopkgtest --no-built-binaries build/debian/grouprise*.dsc -- null
