image: git-registry.hack-hro.de:443/grouprise/grouprise/build:buster
variables:
    # Do not use the 'build/' subdirectory, since this would get cleanup up during 'dist-deb'.
    # This directory needs to be listed in debian/source/options in 'extend-diff-ignore'.
    virtualenv_directory: "$CI_PROJECT_DIR/gitlab-ci-build-venv"

.populate_virtualenv: &populate_virtualenv
    - python3 -m venv --system-site-packages "$virtualenv_directory"
    - source "$virtualenv_directory/bin/activate"
    - pip3 install -r requirements.txt

.build_deb_package:
    script:
        - *populate_virtualenv
        - make dist-deb DEBIAN_BUILDPACKAGE_COMMAND="dpkg-buildpackage -sa --no-sign"
        # turn the symlink of the orig tarball into a real file
        - a=$(ls build/debian/grouprise_*.orig.tar.gz) && cp -L "$a" "$a.tmp" && mv "$a.tmp" "$a"
    artifacts:
        name: grouprise-deb
        paths:
            - build/debian
        exclude:
            # omit the full build directory (including the huge "node_modules" directory)
            - build/debian/grouprise-*/**

make_test:
    stage: test
    script:
        - *populate_virtualenv
        # stadt.settings is required for the tests
        - make app_local_settings
        - make lint
        - make test
    # disable artifacts: otherwise the deb package would be checked by lintian (and fail)
    dependencies: []
    # do not wait for the build jobs
    needs: []

# The latest built deb package is available under the following URL:
#   https://git.hack-hro.de/grouprise/grouprise/builds/artifacts/master/raw/build/debian/export/grouprise.deb?job=deb-package
make_deb_package:
    extends: .build_deb_package
    stage: build
    except:
        - tags
    artifacts:
        expire_in: 1w

make_deb_package_release:
    extends: .build_deb_package
    stage: build
    only:
        - tags
        - web
    artifacts:
        expire_in: 1000 yrs

deb_package_test:
    stage: test
    dependencies:
      - make_deb_package
      - make_deb_package_release
    script:
      # make all built grouprise packages available locally
      - apt-get install -y local-apt-repository
      - mkdir -p /srv/local-apt-repository
      - cp build/debian/*.deb /srv/local-apt-repository/
      - /usr/lib/local-apt-repository/rebuild
      - apt-get update
      # we are running autopkgtest manually, thus we need to install its dependencies
      - "apt-get install -y $(grep '^Depends: ' debian/tests/control | cut -f 2- -d ' ' | tr -d ',' | tr ' ' '\n' | sort | uniq)"
      # install and run autopkgtest
      - apt-get install -y autopkgtest
      - autopkgtest --no-built-binaries build/debian/grouprise*.dsc -- null
