# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
