# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 07:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content2", "0008_auto_20170620_1022"),
        ("files", "0002_file_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file",
                to="content2.Version",
            ),
        ),
    ]
