# Generated by Django 2.2.25 on 2021-12-13 11:29

from django.db import migrations
import grouprise.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_file_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=grouprise.core.fields.DownloadFileField(upload_to=""),
        ),
    ]
