# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_group_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={},
        ),
    ]
