# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20170428_1050'),
    ]

    operations = [
    ]
