# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0010_auto_20170613_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="Adresse der Gruppenseite",
            ),
        ),
    ]
