# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:34
from __future__ import unicode_literals

from django.db import migrations, models

import grouprise.features.groups.models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0011_auto_20170613_1501"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                unique=True,
                validators=[],
                verbose_name="Adresse der Gruppenseite",
            ),
        ),
    ]
