# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import features.stadt.forms


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_auto_20171120_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, help_text='Wird auch als Kurzname verwendet', null=True, unique=True, validators=[features.stadt.forms.validate_entity_slug], verbose_name='Adresse der Gruppenseite'),
        ),
    ]
