# Generated by Django 2.0.8 on 2018-11-19 10:12

import datetime
import pytz
from django.db import migrations, models


def set_time_modified_from_date_created(apps, schema_editor):
    Group = apps.get_model("groups", "Group")
    tz_utc = pytz.timezone("Europe/Berlin")

    for group in Group.objects.all():
        time = datetime.datetime.combine(group.date_created, datetime.time.min)
        group.time_modified = tz_utc.fromutc(time)
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0020_auto_20180206_0913"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="time_modified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            set_time_modified_from_date_created, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="group",
            name="time_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
