# Generated by Django 2.1.9 on 2019-06-24 13:43

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0002_auto_20150616_2121"),
        ("groups", "0023_auto_20190624_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Schlagworte",
            ),
        ),
    ]
