# Generated by Django 2.2.25 on 2021-12-13 10:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0026_auto_20210419_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
