# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 08:59
from __future__ import unicode_literals

import core.colors
import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0043_auto_20160922_1059'),
        ('content', '0028_auto_20160831_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', core.models.AutoSlugField(populate_from='name', reserve=['gestalt', 'stadt'], unique=True, validators=[core.models.validate_reservation], verbose_name='Adresse der Gruppenseite')),
                ('address', models.TextField(blank=True, verbose_name='Anschrift')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('avatar_color', models.CharField(default=core.colors.get_random_color, max_length=7)),
                ('date_founded', models.DateField(blank=True, null=True, verbose_name='Gruppe gegründet')),
                ('description', models.TextField(blank=True, default='', max_length=200, verbose_name='Kurzbeschreibung')),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('url', models.URLField(blank=True, verbose_name='Adresse im Web')),
                ('closed', models.BooleanField(default=False, help_text='Nur Mitglieder können neue Mitglieder aufnehmen.', verbose_name='Geschlossene Gruppe')),
                ('content', models.ManyToManyField(related_name='groups', through='entities.GroupContent', to='content.Content')),
                ('gestalt_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Gestalt')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
