# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20170607_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_founded',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Gruppe gegründet'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Adresse der Gruppenseite'),
        ),
    ]
