# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_auto_20170704_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_founded',
            field=models.DateField(default=datetime.date.today, verbose_name='Gruppe gegründet'),
        ),
    ]
