# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import features.groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_auto_20170704_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='closed',
            field=models.BooleanField(default=False, help_text='In eine geschlossenen Gruppe können nur Mitglieder neue Mitglieder aufnehmen.', verbose_name='Geschlossene Gruppe'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_founded',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Ungefähres Datum der tatsächlichen Gruppengründung', verbose_name='Gruppe gegründet'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Höchstens 200 Zeichen', max_length=200, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, help_text='Wird auch als Kurzname verwendet', null=True, unique=True, validators=[features.groups.models.validate_slug], verbose_name='Adresse der Gruppenseite'),
        ),
        migrations.AlterField(
            model_name='group',
            name='url',
            field=models.URLField(blank=True, verbose_name='Externe Website'),
        ),
        migrations.AlterField(
            model_name='group',
            name='url_import_feed',
            field=models.BooleanField(default=False, help_text='Öffentliche Beiträge der angegebenen Website nach Möglichkeit automatisch in dieser Gruppe veröffentlichen', verbose_name='Beiträge von Website übernehmen'),
        ),
    ]
