# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestalten', '0008_auto_20170704_1729'),
        ('associations', '0003_auto_20170330_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=70)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('gestalt_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestalten.Gestalt')),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.Association')),
            ],
        ),
    ]
