# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 07:47
from __future__ import unicode_literals

from django import db
from django.db import migrations, transaction


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0001_initial'),
    ]

    operations = [
    ]
