# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestalten", "0004_gestalt_addressed_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestalt",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
