# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0008_auto_20170704_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestaltsetting',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='gestaltsetting',
            unique_together=set([('gestalt', 'category', 'name')]),
        ),
    ]
