# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:42
from __future__ import unicode_literals

from django.db import migrations


def rename_gestalten(apps, schema_editor):
    Gestalt = apps.get_model("gestalten", "Gestalt")
    for gestalt in Gestalt.objects.all():
        gestalt.user.username = gestalt.user.username.replace("+", "_")
        gestalt.user.username = gestalt.user.username.replace(".", "_")
        gestalt.user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("gestalten", "0009_auto_20170908_1620"),
    ]

    operations = [
        migrations.RunPython(rename_gestalten),
    ]
