# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestalten", "0010_auto_20171124_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestalt",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Öffentliche Benutzerseiten sind für alle Besucherinnen sichtbar.",
                verbose_name="Benutzerseite veröffentlichen",
            ),
        ),
    ]
