# Generated by Django 2.2.2 on 2019-07-29 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0012_auto_20190618_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestalt',
            name='activity_bookmark_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
