# Generated by Django 3.2.12 on 2022-06-22 14:57

from django.db import migrations, models


def migrate_email_settings(apps, schema_editor):
    Gestalt = apps.get_model("gestalten", "Gestalt")
    db_alias = schema_editor.connection.alias
    for gestalt in Gestalt.objects.using(db_alias):
        gestalt.receives_email_notifications = not gestalt.is_email_blocker
        gestalt.save()


class Migration(migrations.Migration):

    dependencies = [
        ("gestalten", "0016_auto_20210421_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestalt",
            name="receives_builtin_inbox_notifications",
            field=models.BooleanField(
                default=True,
                verbose_name="Empfange Benachrichtigungen auf der Plattform",
            ),
        ),
        migrations.AddField(
            model_name="gestalt",
            name="receives_email_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Empfange Benachrichtigungen per E-Mail"
            ),
        ),
        migrations.AddField(
            model_name="gestalt",
            name="receives_matrix_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Empfange Benachrichtigungen per Matrix-Chat"
            ),
        ),
        migrations.RunPython(migrate_email_settings),
    ]
