# Generated by Django 3.2.12 on 2022-06-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0017_auto_20220622_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestalt',
            name='activity_bookmark_time',
        ),
        migrations.RemoveField(
            model_name='gestalt',
            name='is_email_blocker',
        ),
    ]
