# Generated by Django 3.2.12 on 2022-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0018_auto_20220622_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestalt',
            name='receives_builtin_inbox_notifications',
            field=models.BooleanField(default=True, help_text='Die Benachrichtigungen werden im Benutzer:innenmenü unter "Aktivität" angezeigt.', verbose_name='Empfange Benachrichtigungen auf der Plattform'),
        ),
        migrations.AlterField(
            model_name='gestalt',
            name='receives_email_notifications',
            field=models.BooleanField(default=True, help_text='Die Benachrichtigungen werden per E-Mail an die festgelegte Hauptadresse versendet.', verbose_name='Empfange Benachrichtigungen per E-Mail'),
        ),
        migrations.AlterField(
            model_name='gestalt',
            name='receives_matrix_notifications',
            field=models.BooleanField(default=True, help_text='Die Benachrichtigungen werden in verschiedene Matrix-Räume zugestellt. Sie können auch mit einer App auf mobilen Geräten gelesen werden.', verbose_name='Empfange Benachrichtigungen per Matrix-Chat'),
        ),
    ]
