# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ('time_created',)},
        ),
    ]
