# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_auto_20161111_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='entities.Gestalt'),
        ),
    ]
