# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0006_gestaltsetting'),
        ('texts', '0004_auto_20170112_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestalten.Gestalt')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.Text')),
            ],
        ),
    ]
