# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:18
from __future__ import unicode_literals

from django.db import migrations


def copy_authors(apps, schema_editor):
    Authorship = apps.get_model('texts', 'Authorship')
    Text = apps.get_model('texts', 'Text')
    for text in Text.objects.all():
        a = Authorship.objects.create(author=text.author, text=text)
        a.time_created = text.time_created
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_authorship'),
    ]

    operations = [
        migrations.RunPython(copy_authors),
    ]
