# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_auto_20170223_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replykey',
            name='key',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
