# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0006_gestaltsetting'),
        ('texts', '0006_auto_20170224_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ('authors__time_created',)},
        ),
        migrations.RemoveField(
            model_name='text',
            name='author',
        ),
        migrations.RemoveField(
            model_name='text',
            name='time_created',
        ),
        migrations.AddField(
            model_name='text',
            name='authors',
            field=models.ManyToManyField(through='texts.Authorship', to='gestalten.Gestalt'),
        ),
    ]
