# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0007_auto_20170223_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='in_reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='texts.Text'),
        ),
    ]
