# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0008_text_in_reply_to'),
        ('texts', '0009_auto_20170224_1648'),
    ]

    operations = [
    ]
