# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = []
