# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:15
from __future__ import unicode_literals

from django.db import migrations


def copy_texts(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_texts),
    ]
