# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0006_auto_20170711_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="attached_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="contributions.Contribution",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="in_reply_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="contributions.Contribution",
            ),
        ),
    ]
