# Generated by Django 2.0.1 on 2018-01-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0009_auto_20180109_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="contributions.Contribution",
            ),
        ),
    ]
