# Generated by Django 2.1.8 on 2019-04-07 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0012_contribution_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="time_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
