# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 07:44
from __future__ import unicode_literals

import core.colors
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='Selbstauskunft')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('avatar_color', models.CharField(default=core.colors.get_random_color, max_length=7)),
                ('background', models.ImageField(blank=True, upload_to='', verbose_name='Hintergrundbild')),
                ('public', models.BooleanField(default=False, help_text='Meine Benutzerseite ist für alle Besucherinnen sichtbar.', verbose_name='Benutzerseite veröffentlichen')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, related_name='new_gestalt')),
            ],
        ),
    ]
