# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0052_auto_20170112_1041'),
        ('content', '0031_auto_20170112_1000'),
        ('gestalten', '0003_auto_20170112_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestalt',
            name='addressed_content',
            field=models.ManyToManyField(related_name='gestalten', through='entities.GestaltContent', to='content.Content'),
        ),
    ]
