# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0003_auto_20170112_0940'),
    ]

    operations = [
    ]
