# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0006_gestaltsetting'),
    ]

    operations = [
    ]
