# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 07:34
from __future__ import unicode_literals

from django.db import migrations

import core.models
import core.text


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
    ]
