# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_auto_20170921_1231"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simpleoption",
            old_name="title2",
            new_name="title",
        ),
    ]
