# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_auto_20170921_1232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="endorse",
            field=models.NullBooleanField(default=False),
        ),
    ]
