# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_auto_20180104_1129"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="endorse",
        ),
    ]
