# Generated by Django 2.0.1 on 2018-01-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0012_auto_20180104_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="voter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="votes",
                to="gestalten.Gestalt",
            ),
        ),
    ]
