# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180222_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='poll',
        ),
    ]
