# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0017_auto_20180222_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="poll",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="polls.WorkaroundPoll",
            ),
        ),
    ]
