# Generated by Django 3.2.16 on 2022-12-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20180222_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplevote',
            name='endorse',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
