# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0034_auto_20170209_1451'),
        ('gestalten', '0006_gestaltsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous', models.CharField(blank=True, max_length=63)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Option')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestalten.Gestalt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
