# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='endorse',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
