# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170505_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('id',)},
        ),
    ]
