# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 08:36
from __future__ import unicode_literals

from django.db import connection, migrations


def convert_polls(apps, schema_editor):
    Content = apps.get_model('content2', 'Content')
    Poll = apps.get_model('polls', 'Poll')
    with connection.cursor() as cursor:
        for c in Content.objects.all():
            if c.options.count() > 0:
                cursor.execute('INSERT INTO polls_poll VALUES (%s, 0)', [c.id])


def adapt_options(apps, schema_editor):
    Option = apps.get_model('polls', 'Option')
    for o in Option.objects.all():
        o.poll_new = o.poll.poll
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content2', '0008_auto_20170620_1022'),
        ('polls', '0005_auto_20171212_1637'),
    ]

    operations = [
        migrations.RunPython(convert_polls),
        migrations.RunPython(adapt_options),
    ]
