# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170509_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ('option__id',)},
        ),
    ]
