# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170509_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='endorse',
            field=models.BooleanField(default=False),
        ),
    ]
