# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_option_poll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='poll_new',
            new_name='poll',
        ),
    ]
