# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0006_gestaltsetting'),
        ('polls', '0007_auto_20170509_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='gestalten.Gestalt'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('option', 'voter', 'anonymous')]),
        ),
    ]
