# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0006_gestaltsetting'),
        ('polls', '0008_auto_20170511_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='anonymous',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('option', 'voter'), ('option', 'anonymous')]),
        ),
    ]
