# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170512_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
