# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_vote_endorse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplevote',
            old_name='endorse_new',
            new_name='endorse',
        ),
    ]
