# Generated by Django 2.0.2 on 2018-02-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180104_1149'),
        ('polls', '0005_auto_20180109_1302'),
    ]

    operations = [
    ]
