# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_merge_20180209_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ('time_updated',)},
        ),
    ]
