# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content2', '0009_auto_20180109_1302'),
        ('galleries', '0004_auto_20170427_0844'),
        ('polls', '0013_merge_20180209_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='option',
            name='poll',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
