# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content2', '0009_auto_20180109_1302'),
        ('polls', '0014_auto_20180219_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condorcet', models.BooleanField(default=False)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='content2.Content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.Poll'),
        ),
    ]
