# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180219_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='content',
        ),
    ]
