# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180215_0009'),
        ('polls', '0016_remove_poll_content'),
    ]

    operations = [
    ]
