# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_auto_20170427_0844'),
        ('content2', '0010_content_poll_new'),
        ('polls', '0016_remove_option_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='content_ptr',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='poll_new',
            new_name='poll',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
