# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content2", "0003_auto_20170330_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="all_day",
            field=models.BooleanField(
                default=False,
                help_text="Das Ereignis dauert den gesamten Tag.",
                verbose_name="ganztägig",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="place",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Veranstaltungsort / Anschrift"
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Beginn"),
        ),
        migrations.AddField(
            model_name="content",
            name="until_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ende"),
        ),
    ]
