# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 10:03
from __future__ import unicode_literals

from django.db import migrations

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('content2', '0004_auto_20170413_1159'),
    ]

    operations = [
    ]
