# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_auto_20170421_0911"),
        ("content2", "0006_auto_20170421_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="images.Image",
            ),
        ),
    ]
