# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content2', '0010_content_poll_new'),
        ('polls', '0015_auto_20180222_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='poll_new',
            new_name='poll',
        ),
    ]
