# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 10:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content2", "0011_auto_20180222_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="poll",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to="polls.WorkaroundPoll",
            ),
        ),
    ]
