# Generated by Django 2.2.25 on 2022-04-06 08:10

from django.db import migrations


def remove_all_file_objects_but_last(apps, _):
    Content = apps.get_model("content2", "Content")
    File = apps.get_model("files", "File")
    for content in Content.objects.all():
        latest_version = content.versions.order_by("time_created").last()
        if latest_version is not None:
            prev_versions = content.versions.exclude(pk=latest_version.pk)
            File.objects.filter(version__in=prev_versions).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("content2", "0017_content_tags"),
        ("files", "0006_fix_redirects"),
    ]

    operations = [
        migrations.RunPython(remove_all_file_objects_but_last),
    ]
