# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 07:23
from __future__ import unicode_literals

from django.db import migrations


def move_subscriptions(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    GroupAttention = apps.get_model('entities', 'GroupAttention')
    Subscription = apps.get_model('subscriptions', 'Subscription')
    for attention in GroupAttention.objects.all():
        Subscription.objects.create(
                content_type=ContentType.objects.get_for_model(attention.group),
                object_id=attention.group.id,
                subscriber=attention.attendee)


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0035_auto_20160705_0754'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(move_subscriptions),
    ]
