# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20160705_0923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('content_type', 'object_id', 'subscriber')]),
        ),
    ]
