# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20160705_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='unsubscribe',
            field=models.BooleanField(default=False),
        ),
    ]
