# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20160923_0900'),
        ('subscriptions', '0005_filter'),
    ]

    operations = [
    ]
