# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_unsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrUnsubscription',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('subscriptions.subscription',),
        ),
    ]
