# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20170918_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='unsubscribe',
        ),
    ]
