#!/usr/bin/dh-exec
debian/grouprise.uwsgi.ini => /etc/uwsgi/apps-available/grouprise.ini
debian/grouprise.settings.py => /etc/grouprise/settings.py
debian/grouprisectl => /usr/bin/grouprisectl
debian/README.backups => /var/backups/grouprise/README
debian/tmp/usr/share/grouprise/stadt /usr/share/grouprise/grouprise/
debian/tmp/usr/share/grouprise/core /usr/share/grouprise/grouprise/
debian/tmp/usr/share/grouprise/features /usr/share/grouprise/grouprise/
debian/tmp/usr/share/grouprise/manage.py /usr/share/grouprise/grouprise/
