#!/bin/sh

set -eu

EXEC_USER=grouprise
MANAGE_BIN=/usr/share/grouprise/grouprise/manage.py
EXTRA_PYTHON_PATHS=/usr/share/grouprise/grouprise:/usr/share/grouprise/virtualenv

if [ "$(id -nu)" = "$EXEC_USER" ]; then
    if [ -z "${PYTHONPATH:-}" ]; then
        PYTHONPATH=$EXTRA_PYTHON_PATHS
    else
        PYTHONPATH=$EXTRA_PYTHON_PATHS:$PYTHONPATH
    fi
    export PYTHONPATH
    python3 "$MANAGE_BIN" "$@"
elif [ "$(id -u)" = 0 ]; then
    su -s "$0" "$EXEC_USER" -- "$@"
else
    echo "please run stadtctl as root or '$EXEC_USER'" >&2
    exit 1
fi
