# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:06
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20170209_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', core.models.AutoSlugField(populate_from='name', reserve=[], unique=True, validators=[core.models.validate_reservation])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='tagged',
            options={},
        ),
    ]
