# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:40
from __future__ import unicode_literals

from core.utils import slugify
from django.db import migrations


def merge_tags(apps, schema_editor):
    Tag = apps.get_model('tags', 'Tag')
    Tagged = apps.get_model('tags', 'Tagged')
    for tagged in Tagged.objects.all():
        slug = slugify(None, None, tagged.name, dodging=False)
        tag, created = Tag.objects.get_or_create(slug=slug, defaults={'name': tagged.name})
        tagged.tag = tag
        tagged.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20170209_1540'),
    ]

    operations = [
        migrations.RunPython(merge_tags),
    ]
