# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_auto_20170209_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagged',
            name='name',
        ),
        migrations.AlterField(
            model_name='tagged',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag'),
        ),
    ]
