# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_auto_20170711_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
