# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 15:21
from __future__ import unicode_literals

from django.db import migrations
import itertools


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
    ]
