# Generated by Django 2.2 on 2022-06-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builtin_inbox_notifications', '0004_builtininboxnotification_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtininboxnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
