# Generated by Django 2.2.25 on 2021-12-23 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locatable_id', models.PositiveIntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('locatable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('locatable_type', 'locatable_id'), name='locatable_location'),
        ),
    ]
