# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_auto_20160718_1052"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membership",
            old_name="gestalt",
            new_name="member",
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set([("group", "member")]),
        ),
    ]
