# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 17:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("memberships", "0006_auto_20160811_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="groups.Group",
            ),
        ),
    ]
