# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("memberships", "0007_auto_20160830_1911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="groups.Group",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set([]),
        ),
    ]
