# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0008_auto_20160923_0851"),
    ]

    operations = []
