# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0009_auto_20170607_1402"),
        ("memberships", "0012_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="groups.Group",
            ),
        ),
    ]
