# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0013_application_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='groups.Group'),
        ),
    ]
