# Generated by Django 2.0.1 on 2018-01-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0014_auto_20170609_1029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships_created",
                to="gestalten.Gestalt",
            ),
        ),
    ]
