# Generated by Django 2.2.4 on 2019-08-06 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0013_auto_20190408_0027"),
        ("memberships", "0016_auto_20190408_0027"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="attached_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_applications",
                to="contributions.Contribution",
            ),
        ),
    ]
