# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='date_founded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
