# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0002_auto_20151217_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestalt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
