# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20151217_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
