# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_gestalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
