# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='logo',
            new_name='avatar',
        ),
    ]
