# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('entities', '0006_auto_20151226_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Group')),
            ],
        ),
    ]
