# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_groupcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestalt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
