# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20151227_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
