# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_group_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('gestalt', 'group')]),
        ),
    ]
