# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20151228_1452_squashed_0012_auto_20160106_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestalt',
            name='about',
            field=models.TextField(blank=True, verbose_name='Selbstauskunft'),
        ),
        migrations.AddField(
            model_name='gestalt',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.TextField(blank=True, verbose_name='Anschrift'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_founded',
            field=models.DateField(blank=True, null=True, verbose_name='Gruppe gegründet'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Adresse der Gruppenseite'),
        ),
        migrations.AlterField(
            model_name='group',
            name='url',
            field=models.URLField(blank=True, verbose_name='Adresse im Web'),
        ),
    ]
