# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_content_views'),
        ('entities', '0013_auto_20160108_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadtgestalten', models.BooleanField()),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
                ('gestalt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Gestalt')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.Group')),
            ],
        ),
    ]
