# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestalt',
            name='avatar',
            field=models.ImageField(default='/stadt/static/avatar.png', upload_to=''),
        ),
    ]
