# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20160120_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcontent',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
