# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_auto_20160212_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(default='/stadt/static/avatar.png', upload_to=''),
        ),
    ]
