# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0018_group_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcontent',
            options={'ordering': ('-content__date_created',)},
        ),
    ]
