# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20160405_1115'),
        ('entities', '0019_auto_20160315_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestaltContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
                ('gestalt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Gestalt')),
            ],
        ),
        migrations.AlterModelOptions(
            name='groupcontent',
            options={},
        ),
        migrations.AddField(
            model_name='group',
            name='content',
            field=models.ManyToManyField(related_name='groups', through='entities.GroupContent', to='content.Content'),
        ),
    ]
