# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20160405_1512'),
        ('entities', '0020_auto_20160405_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestalt',
            name='addressed_content',
            field=models.ManyToManyField(related_name='gestalten', through='entities.GestaltContent', to='content.Content'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='entities.Membership', to='entities.Gestalt'),
        ),
    ]
