# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_auto_20160405_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Gestalt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='attention',
            name='content',
        ),
        migrations.RemoveField(
            model_name='attention',
            name='gestalt',
        ),
        migrations.RemoveField(
            model_name='attention',
            name='group',
        ),
        migrations.DeleteModel(
            name='Attention',
        ),
    ]
