# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0022_auto_20160411_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_groups', through='entities.GroupAttention', to='entities.Gestalt'),
        ),
    ]
