# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0023_group_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
