# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0025_group_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar_color',
            field=models.CharField(default='#17a53a', max_length=7),
        ),
    ]
