# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0025_group_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestalt',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
