# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0026_auto_20160602_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',)},
        ),
    ]
