# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0029_auto_20160607_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestalt',
            name='background',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
