# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0032_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestalt',
            name='public',
            field=models.BooleanField(default=False, help_text='Es wird eine Benutzerseite angelegt, auf der alle Beiträge der Benutzerin sichtbar sind.', verbose_name='Benutzerseite veröffentlichen'),
        ),
    ]
