# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0033_gestalt_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestalt',
            name='public',
            field=models.BooleanField(default=False, help_text='Meine Benutzerseite ist für alle Besucherinnen sichtbar.', verbose_name='Benutzerseite veröffentlichen'),
        ),
    ]
