# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0034_auto_20160629_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attention',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='attention',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Attention',
        ),
    ]
