# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0035_auto_20160705_0754'),
        ('subscriptions', '0002_auto_20160705_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupattention',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='groupattention',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='GroupAttention',
        ),
    ]
