# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 08:41
from __future__ import unicode_literals

import core.colors
from django.db import migrations, models


def set_default_colors(apps, schema_editor):
    Gestalt = apps.get_model('entities', 'Gestalt')
    for gestalt in Gestalt.objects.all():
        gestalt.avatar_color = entities.models.get_random_color()
        gestalt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0036_auto_20160705_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestalt',
            name='avatar_color',
            field=models.CharField(default=core.colors.get_random_color, max_length=7),
        ),

        migrations.RunPython(set_default_colors),
    ]
