# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0037_gestalt_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='gestalt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_memberships', to='entities.Gestalt'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_memberships', to='entities.Group'),
        ),
    ]
