# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 07:05
from __future__ import unicode_literals

from django.db import migrations


def add_group(apps, schema_editor):
    Group = apps.get_model('entities', 'Group')
    if not Group.objects.exists():
        Group.objects.create(name='Stadtgestalten')


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0037_gestalt_avatar_color'),
    ]

    operations = [
        migrations.RunPython(add_group)
    ]
