# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0039_auto_20160718_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
