# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0040_remove_group_members'),
        ('entities', '0038_auto_20160719_0905'),
    ]

    operations = [
    ]
