# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0042_group_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='content',
        ),
    ]
