# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0045_auto_20160922_1330'),
        ('memberships', '0009_auto_20160923_0852'),
        ('subscriptions', '0004_auto_20160923_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
