# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0049_auto_20170112_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestalt',
            name='addressed_content',
        ),
        migrations.AlterField(
            model_name='gestaltcontent',
            name='gestalt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestalten.Gestalt'),
        ),
    ]
