# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0050_auto_20170112_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestalt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='old_gestalt', to=settings.AUTH_USER_MODEL),
        ),
    ]
