# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content2', '0005_auto_20170413_1203'),
        ('conversations', '0002_auto_20161110_1621'),
        ('gestalten', '0007_remove_gestalt_addressed_content'),
        ('galleries', '0002_auto_20170421_0934'),
        ('groups', '0009_auto_20170607_1402'),
        ('entities', '0052_auto_20170112_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestaltcontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='gestaltcontent',
            name='gestalt',
        ),
        migrations.RemoveField(
            model_name='groupcontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='groupcontent',
            name='group',
        ),
        migrations.DeleteModel(
            name='GestaltContent',
        ),
        migrations.DeleteModel(
            name='GroupContent',
        ),
    ]
