# Generated by Django 2.2.17 on 2021-01-17 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestalten", "0014_auto_20190815_0926"),
        ("groups", "0024_group_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatrixChatGroupRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=256)),
                ("is_private", models.BooleanField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_rooms",
                        to="groups.Group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrixChatGestaltSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matrix_id_override", models.CharField(blank=True, max_length=256)),
                (
                    "gestalt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_chat_settings",
                        to="gestalten.Gestalt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrixChatGroupRoomInvitations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_invited", models.DateTimeField(auto_now=True)),
                (
                    "gestalt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gestalten.Gestalt",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="matrix_chat.MatrixChatGroupRoom",
                    ),
                ),
            ],
        ),
    ]
