# Generated by Django 2.2.24 on 2021-07-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matrixchatgrouproom",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
