# Generated by Django 2.2.24 on 2021-07-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matrix_chat", "0002_matrixchatgrouproom_is_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="matrixchatgrouproom",
            name="statistics_cache_json",
            field=models.CharField(default="{}", max_length=4096),
        ),
    ]
