# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
