# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_event_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
