# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20151227_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.RemoveField(
            model_name='content',
            name='views',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-date_created',)},
        ),
    ]
