# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:56
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20151227_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
