# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content_slug_squashed_0012_auto_20160215_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('time',)},
        ),
    ]
