# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20151228_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
