# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0018_group_members'),
        ('content', '0007_auto_20160307_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='groups',
            field=models.ManyToManyField(through='entities.GroupContent', to='entities.Group'),
        ),
    ]
