# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20151228_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='views',
        ),
    ]
