# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 11:12
from __future__ import unicode_literals

from django.db import migrations, models

def publish_content(apps, schema_editor):
    Content = apps.get_model('content', 'Content')
    for content in Content.objects.all():
        content.public = True
        content.save()

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_content_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='public',
            field=models.BooleanField(default=False, help_text='Veröffentlichter Inhalt wird im öffentlichen Blog angezeigt, Benachrichtigungen werden an Gruppenmitglieder und Beobachterinnen versendet. Nicht veröffentlichter Inhalt ist nur gruppenintern zugänglich, Benachrichtigungen werden nur an Mitglieder versendet.', verbose_name='Veröffentlicht'),
        ),
        migrations.RunPython(publish_content),
    ]
