# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='public',
            field=models.BooleanField(default=False, help_text='Veröffentlichter Inhalt wird im öffentlichen Blog angezeigt, Benachrichtigungen werden an Gruppenmitglieder und Beobachterinnen versendet. Nicht veröffentlichter Inhalt ist nur gruppenintern zugänglich, Benachrichtigungen werden nur an Mitglieder versendet.', verbose_name='Veröffentlichen'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel / Betreff'),
        ),
    ]
