# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20160315_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(verbose_name='Datum / Uhrzeit'),
        ),
    ]
