# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20160215_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
