# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20160322_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='groups',
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
    ]
