# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20160405_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='public',
            field=models.BooleanField(default=False, help_text='Veröffentlichte Beiträge sind auch für Besucherinnen sichtbar, die nicht Mitglied der Gruppe sind.', verbose_name='Veröffentlichen'),
        ),
    ]
