# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20160428_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.Content'),
        ),
    ]
