# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0025_group_avatar_color'),
        ('content', '0018_auto_20160524_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='comment_authors',
            field=models.ManyToManyField(through='content.Comment', to='entities.Gestalt'),
        ),
    ]
