# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_content_comment_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_created',)},
        ),
    ]
