# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20160524_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
