# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 12:07
from __future__ import unicode_literals

from django.db import migrations, models


def set_weights(apps, schema_editor):
    Image = apps.get_model('content', 'Image')
    for image in Image.objects.all():
        image.weight = image.id - image.content.images.first().id
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20160525_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('weight',)},
        ),
        migrations.AddField(
            model_name='image',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(set_weights),
    ]
