# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20160614_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Ort / Anschrift'),
        ),
    ]
