# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20160616_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
