# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20160630_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.Content'),
        ),
    ]
