# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0042_group_closed'),
        ('content', '0026_auto_20160726_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_image', to='entities.Gestalt'),
        ),
    ]
