# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0046_delete_group'),
        ('content', '0028_auto_20160831_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='additional_authors',
            field=models.ManyToManyField(related_name='additional_authorship', to='entities.Gestalt'),
        ),
        migrations.AlterField(
            model_name='content',
            name='comment_authors',
            field=models.ManyToManyField(related_name='comments', through='content.Comment', to='entities.Gestalt'),
        ),
    ]
