# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 08:38
from __future__ import unicode_literals

from django.db import migrations


def delete_conversation_content(apps, schema_editor):
    Article = apps.get_model('content.Article')
    Article.objects.filter(public=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20161103_1203'),
        ('conversations', '0002_auto_20161110_1621'),
    ]

    operations = [
        migrations.RunPython(delete_conversation_content),
    ]
