# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20161125_0938'),
        ('gestalten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_comment', to='gestalten.Gestalt'),
        ),
        migrations.AlterField(
            model_name='content',
            name='additional_authors',
            field=models.ManyToManyField(related_name='additional_authorship', to='gestalten.Gestalt'),
        ),
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_content', to='gestalten.Gestalt'),
        ),
        migrations.AlterField(
            model_name='content',
            name='comment_authors',
            field=models.ManyToManyField(related_name='comments', through='content.Comment', to='gestalten.Gestalt'),
        ),
        migrations.AlterField(
            model_name='image',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gestalten.Gestalt'),
        ),
    ]
