# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20170105_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='until_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum / Uhrzeit Ende'),
        ),
    ]
