# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20170105_0932'),
        ('content', '0031_auto_20170112_1000'),
    ]

    operations = [
    ]
