# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_auto_20170209_1451'),
        ('images', '0002_auto_20170421_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content',
        ),
        migrations.RemoveField(
            model_name='image',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
