# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20170428_1050'),
        ('entities', '0052_auto_20170112_1041'),
        ('gestalten', '0006_gestaltsetting'),
        ('content', '0035_auto_20170508_1109'),
        ('galleries', '0002_auto_20170421_0934'),
    ]

    operations = [
        # migrations.RemoveField(
        #    model_name='gallery',
        #    name='content_ptr',
        # ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
