# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0052_auto_20170112_1041'),
        ('gestalten', '0006_gestaltsetting'),
        ('content', '0036_auto_20170512_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='content_ptr',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
