# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestalten', '0006_gestaltsetting'),
        ('entities', '0052_auto_20170112_1041'),
        ('content', '0037_auto_20170609_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
