# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_auto_20170609_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='comment_authors',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
