# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content2', '0001_initial'),
        ('entities', '0053_auto_20170609_1443'),
        ('gestalten', '0007_remove_gestalt_addressed_content'),
        ('content', '0039_auto_20170609_1441'),
        ('groups', '0009_auto_20170607_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='additional_authors',
        ),
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
