# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.PositiveIntegerField()),
                ('entity_id', models.PositiveIntegerField()),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_associations', to='contenttypes.ContentType')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_associations', to='contenttypes.ContentType')),
            ],
        ),
    ]
