# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0003_auto_20170330_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
