# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:55
from __future__ import unicode_literals

from django.db import migrations

import core.models
import core.text


class Migration(migrations.Migration):

    dependencies = [
        ('content2', '0001_initial'),
    ]

    operations = [
    ]
