# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 07:49
from __future__ import unicode_literals

from django.db import migrations
import itertools


def copy_articles(apps, schema_editor):
    Article = apps.get_model('content.Article')
    Association = apps.get_model('associations.Association')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Content = apps.get_model('content2.Content')
    GestaltContent = apps.get_model('entities.GestaltContent')
    GroupContent = apps.get_model('entities.GroupContent')
    Text = apps.get_model('texts.Text')

    for a in Article.objects.all():
        content = Content.objects.create(title=a.title)
        
        for c in itertools.chain([a], a.comments.all()):
            Text.objects.create(
                    container_type=ContentType.objects.get_for_model(content),
                    container_id=content.id,
                    author=c.author, time_created=c.date_created, text=c.text)
        
        for gc in GestaltContent.objects.filter(content__article=a):
            Association.objects.create(
                    container_type=ContentType.objects.get_for_model(content),
                    container_id=content.id,
                    entity_type=ContentType.objects.get_for_model(gc.gestalt),
                    entity_id=gc.gestalt.id,
                    public=a.public,
                    slug=a.slug)
        
        for gc in GroupContent.objects.filter(content__article=a):
            Association.objects.create(
                    container_type=ContentType.objects.get_for_model(content),
                    container_id=content.id,
                    entity_type=ContentType.objects.get_for_model(gc.group),
                    entity_id=gc.group.id,
                    public=a.public,
                    slug=a.slug)


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0002_auto_20170224_0910'),
        ('content', '0034_auto_20170209_1451'),
        ('content2', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('entities', '0052_auto_20170112_1041'),
        ('texts', '0004_auto_20170112_1000'),
    ]

    operations = [
        migrations.RunPython(copy_articles),
    ]
