# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 10:03
from __future__ import unicode_literals

from django.db import migrations

import core.models
import core.text


def copy_events(apps, schema_editor):
    Event = apps.get_model('content.Event')
    Association = apps.get_model('associations.Association')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Content = apps.get_model('content2.Content')
    Contribution = apps.get_model('contributions.Contribution')
    GestaltContent = apps.get_model('entities.GestaltContent')
    GroupContent = apps.get_model('entities.GroupContent')
    Text = apps.get_model('contributions.Text')
    Version = apps.get_model('content2.Version')

    for e in Event.objects.all():
        content = Content.objects.create(
                title=e.title, place=e.place, time=e.time, until_time=e.until_time,
                all_day=e.all_day)
        v = Version.objects.create(content=content, author=e.author, text=e.text)
        v.time_created = e.date_created
        v.save()
        
        for g in e.additional_authors.all():
            Version.objects.create(content=content, author=g, text=e.text)

        for c in e.comments.all():
            t = Text.objects.create(text=c.text)
            contrib = Contribution.objects.create(
                    container_type=ContentType.objects.get_for_model(content),
                    container_id=content.id,
                    author=c.author, contribution_id=t.id,
                    contribution_type=ContentType.objects.get_for_model(t))
            contrib.time_created = c.date_created
            contrib.save()
        
        gc = None
        for gc in GroupContent.objects.filter(content__event=e):
            slug = e.slug or core.models.get_unique_slug(
                    Association, {
                        'entity_id': gc.group.id,
                        'entity_type': ContentType.objects.get_for_model(gc.group),
                        'slug': core.text.slugify(e.title),
                        })
            Association.objects.create(
                    container_type=ContentType.objects.get_for_model(content),
                    container_id=content.id,
                    entity_type=ContentType.objects.get_for_model(gc.group),
                    entity_id=gc.group.id,
                    pinned=gc.pinned,
                    public=e.public,
                    slug=slug)
            
        if gc is None:
            slug = e.slug or core.models.get_unique_slug(
                    Association, {
                        'entity_id': e.author.id,
                        'entity_type': ContentType.objects.get_for_model(e.author),
                        'slug': core.text.slugify(e.title),
                        })
            Association.objects.create(
                    container_type=ContentType.objects.get_for_model(content),
                    container_id=content.id,
                    entity_type=ContentType.objects.get_for_model(e.author),
                    entity_id=e.author.id,
                    public=e.public,
                    slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('content2', '0004_auto_20170413_1159'),
        ('associations', '0003_auto_20170330_1041'),
        ('content', '0034_auto_20170209_1451'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('contributions', '0002_auto_20170309_1515'),
        ('entities', '0052_auto_20170112_1041'),
    ]

    operations = [
        migrations.RunPython(copy_events),
    ]
