# Generated by Django 3.2.1 on 2022-10-05 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_repeatabletask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepeatableTask',
        ),
    ]
