# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = []
