# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 07:00
from __future__ import unicode_literals

from django.contrib.contenttypes import models as contenttypes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_auto_20160705_1143"),
    ]

    operations = []
