# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_merge_20161006_1014"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unsubscription",
            fields=[],
            options={
                "proxy": True,
            },
            bases=("subscriptions.subscription",),
        ),
    ]
