# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 09:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_suborunsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestalten.Gestalt"
            ),
        ),
    ]
